name: Trigger CircleCI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: dev

jobs:
  trigger-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.2.0
        env:
          CCI_TOKEN: ${{ secrets.PIX_SERVICE_CIRCLE_CI_TOKEN }}
